config/routes.rb
Rails.application.routes.draw do
  resources :ad_hoc_downloads
  resource :rss, only: :show, :controller => :rss

  root 'ad_hoc_downloads#index'

end

app/models/ad_hoc_download.rb
class AdHocDownload < ActiveRecord::Base
  validates_presence_of :url

  def name
    self[:name].blank? ? basename : self[:name]
  end

  def basename
    File.basename(url)
  end
end

app/controllers/ad_hoc_downloads_controller.rb
require 'csv'

class AdHocDownloadsController < ApplicationController
  before_action :set_ad_hoc_download, only: [:show, :edit, :update, :destroy]

  def index
    @ad_hoc_downloads = AdHocDownload.all

    respond_to do |format|
      format.html do
        @ad_hoc_downloads = @ad_hoc_downloads.order('created_at desc')
        render :index
      end

      format.csv do
        @ad_hoc_downloads = @ad_hoc_downloads.where(seen: nil)

        lines = @ad_hoc_downloads.
          map { |d| 
            csv = [d.name, d.url].to_csv
            # Skip instead of choke at the downloader
            csv unless csv.match(/"/)
          }.
          compact

        lines.unshift("name,url\n")

        @ad_hoc_downloads.update_all(seen: true)

        render text: lines.join
      end
    end
  end

  def show
  end

  def new
    @ad_hoc_download = AdHocDownload.new
  end

  def edit
  end

  def create
    @ad_hoc_download = AdHocDownload.new(ad_hoc_download_params)

    respond_to do |format|
      if @ad_hoc_download.save
        format.html { redirect_to ad_hoc_downloads_path, notice: 'Ad hoc download was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @ad_hoc_download.update(ad_hoc_download_params)
        format.html { redirect_to @ad_hoc_download, notice: 'Ad hoc download was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @ad_hoc_download.destroy
    respond_to do |format|
      format.html { redirect_to ad_hoc_downloads_url, notice: 'Ad hoc download was successfully destroyed.' }
    end
  end

  private

  def set_ad_hoc_download
    @ad_hoc_download = AdHocDownload.find(params[:id])
  end

  def ad_hoc_download_params
    params.require(:ad_hoc_download).permit(:name, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  force_ssl if: :force_ssl?
  http_basic_authenticate_with name: ENV['DOCCASTER_AUTH_NAME'], password: ENV['DOCCASTER_AUTH_PASSWORD']

  private

  def force_ssl?
    Rails.env.production? && !request.user_agent.match('TinyTinyNAS')
  end
end

app/controllers/rss_controller.rb
require 'csv'
require 'iconv'
require 'open-uri'
require 'rss'

class RssController < ApplicationController
  def show
    respond_to do |format|
      format.csv do
        lines = open(params[:feed_url]) { |raw|
          feed = RSS::Parser.parse(raw)

          feed.entries.map { |item|
            enclosure = item.
              links.
              find { |l| l.rel == 'enclosure' }

            if enclosure
              url = enclosure.href

              updated = item.updated.content.to_date.iso8601
              source = clean(item.source.title.content)
              title = clean(item.title.content)
              extname = File.extname(url)

              filename = "#{updated} - #{source} - #{title}#{extname}"
              [filename, url].to_csv
            end
          }.compact
        }

        lines.unshift("name,url\n")
        render text: lines.flatten.join
      end
    end
  end

  private

  def clean(s)
    Iconv.conv('ASCII//IGNORE', 'UTF8', s.gsub(/[,"]/, '_'))
  end
end

app/helpers/ad_hoc_downloads_helper.rb
module AdHocDownloadsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ad_hoc_downloads/_form.html.erb
<%= form_for(@ad_hoc_download) do |f| %>
  <% if @ad_hoc_download.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad_hoc_download.errors.count, "error") %> prohibited this ad_hoc_download from being saved:</h2>

      <ul>
      <% @ad_hoc_download.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ad_hoc_downloads/edit.html.erb
<h1>Editing Ad-hoc Download</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad_hoc_download %> |
<%= link_to 'Back', ad_hoc_downloads_path %>

app/views/ad_hoc_downloads/index.html.erb
<h1>Ad-hoc Downloads</h1>

<%= link_to 'Add', new_ad_hoc_download_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Seen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ad_hoc_downloads.each do |ad_hoc_download| %>
      <tr>
        <td><%= link_to(ad_hoc_download.name, ad_hoc_download.url) %></td>
        <td><%= ad_hoc_download.seen ? '&#x2713;'.html_safe : '' %></td>
        <td><%= link_to 'Edit', edit_ad_hoc_download_path(ad_hoc_download) %></td>
        <td><%= link_to 'Destroy', ad_hoc_download, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ad_hoc_downloads/new.html.erb
<h1>New Ad-Hoc Download</h1>

<%= render 'form' %>

<%= link_to 'Back', ad_hoc_downloads_path %>

app/views/ad_hoc_downloads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ad_hoc_download.name %>
</p>

<p>
  <strong>URL:</strong>
  <%= @ad_hoc_download.url %>
</p>

<p>
  <strong>Seen:</strong>
  <%= @ad_hoc_download.seen %>
</p>

<%= link_to 'Edit', edit_ad_hoc_download_path(@ad_hoc_download) %> |
<%= link_to 'Back', ad_hoc_downloads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <title>Doccaster</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>